version: '2'
services:
  vehicle-service:
    # you can change the integra from which the dump is taken in the Dockerfile
    build: ./vehicle-service-integra/
    ports:
      - "127.0.0.1:8081:80"
  zookeeper:
    image: jplock/zookeeper:3.4.8
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:0.9.0.1
    container_name: kafka
    ports:
      - "127.0.0.1:9092:9092"
    links:
      - zookeeper:zk
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "127.0.0.1"
      KAFKA_ADVERTISED_PORT: "9092"
      KAFKA_ZOOKEEPER_CONNECT: "zk:2181"
      KAFKA_CREATE_TOPICS: "inventory_service_vehicles:1:1"
      KAFKA_BROKER_ID: -1
    command: "bash -c 'sleep 2; start-kafka.sh'"
  es:
    image: elasticsearch:1.7
    container_name: es
    # es head plugin can be opened with http://localhost:9200/_plugin/head/
    entrypoint: "bash -c 'plugin -install mobz/elasticsearch-head/1.x; /docker-entrypoint.sh elasticsearch --cluster.name=dev'"
    ports:
    - "127.0.0.1:9300:9300"
    - "127.0.0.1:9200:9200"
  graphite:
    image: hopsoft/graphite-statsd
    ports:
    - "127.0.0.1:9080:80"
    - "127.0.0.1:2003:2003"
    - "127.0.0.1:8125:8125/udp"
